# Generated by Django 4.2.2 on 2023-07-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultation_journaliere',
        ),
        migrations.DeleteModel(
            name='Consultation_VMA',
        ),
    ]
