# Generated by Django 4.2.2 on 2023-07-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_delete_consultation_journaliere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom_prenoms', models.CharField(max_length=200)),
                ('consultation_date', models.DateField(auto_now_add=True)),
                ('reasons', models.CharField(max_length=100)),
                ('aptitude', models.CharField(max_length=100)),
            ],
        ),
    ]
