# Generated by Django 4.2.2 on 2023-07-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterModelOptions(
            name='day_consultation',
            options={'ordering': ['consultation_date'], 'verbose_name_plural': 'Consultations Journalières'},
        ),
        migrations.RemoveField(
            model_name='day_consultation',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='periodic_consultation',
            name='worker',
        ),
        migrations.AddField(
            model_name='day_consultation',
            name='atelier',
            field=models.CharField(blank=True, choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('BOURBON', 'BOURBON'), ('CHAUDRONNERIE', 'CHAUDRONNERIE'), ('CHARPENTE MENUISERIE', 'CHARPENTE MENUISERIE'), ('COMPTABILITE FINANCE', 'COMPTABILITE FINANCE'), ('ELECTRICITE', 'ELECTRICITE'), ('G4S', 'G4S'), ('INFORMATIQUE ET TELECOM', 'INFORMATIQUE ET TELECOM'), ('IRIS', 'IRIS'), ('MAGASIN', 'MAGASIN'), ('MACHINE OUTILS', 'MACHINE OUTILS'), ('MAINTENANCE & TRAVAUX NEUFS', 'MAINTENANCE & TRAVAUX NEUFS'), ('MANUTENTION ET LEVAGE', 'MANUTENTION ET LEVAGE'), ('MECANIQUE BRD', 'MECANIQUE BRD'), ('NAVIRE', 'NAVIRE'), ('NETTOYAGE INDUSTRIEL', 'NETTOYAGE INDUSTRIEL'), ('PEINTURE', 'PEINTURE'), ('PEINTURE ANTICORROSION', 'PEINTURE ANTICORROSION'), ('PRODUCTION', 'PRODUCTION'), ('QUALITE ENVIRONNEMENT HYGIENE', 'QUALITE ENVIRONNEMENT HYGIENE'), ('QUALITE ENVIRONNEMENT HYGIENE ET SECURITE', 'QUALITE ENVIRONNEMENT HYGIENE ET SECURITE'), ('QHSE', 'QHSE'), ('RESSOURCES HUMAINES', 'RESSOURCES HUMAINES'), ('SAUVETAGE', 'SAUVETAGE'), ('SUPPLY CHAIN', 'SUPPLY CHAIN'), ('TUYAUTERIE', 'TUYAUTERIE'), ('WICS', 'WICS')], max_length=100),
        ),
        migrations.AddField(
            model_name='day_consultation',
            name='societe',
            field=models.CharField(blank=True, choices=[('CARENA', 'CARENA'), ('REGIE', 'REGIE'), ('PRESTATAIRE', 'PRESTATAIRE'), ('AGENT DE BORD', 'AGENT DE BORD')], max_length=50),
        ),
        migrations.AddField(
            model_name='periodic_consultation',
            name='atelier',
            field=models.CharField(blank=True, choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('BOURBON', 'BOURBON'), ('CHAUDRONNERIE', 'CHAUDRONNERIE'), ('CHARPENTE MENUISERIE', 'CHARPENTE MENUISERIE'), ('COMPTABILITE FINANCE', 'COMPTABILITE FINANCE'), ('ELECTRICITE', 'ELECTRICITE'), ('G4S', 'G4S'), ('INFORMATIQUE ET TELECOM', 'INFORMATIQUE ET TELECOM'), ('IRIS', 'IRIS'), ('MAGASIN', 'MAGASIN'), ('MACHINE OUTILS', 'MACHINE OUTILS'), ('MAINTENANCE & TRAVAUX NEUFS', 'MAINTENANCE & TRAVAUX NEUFS'), ('MANUTENTION ET LEVAGE', 'MANUTENTION ET LEVAGE'), ('MECANIQUE BRD', 'MECANIQUE BRD'), ('NAVIRE', 'NAVIRE'), ('NETTOYAGE INDUSTRIEL', 'NETTOYAGE INDUSTRIEL'), ('PEINTURE', 'PEINTURE'), ('PEINTURE ANTICORROSION', 'PEINTURE ANTICORROSION'), ('PRODUCTION', 'PRODUCTION'), ('QUALITE ENVIRONNEMENT HYGIENE', 'QUALITE ENVIRONNEMENT HYGIENE'), ('QUALITE ENVIRONNEMENT HYGIENE ET SECURITE', 'QUALITE ENVIRONNEMENT HYGIENE ET SECURITE'), ('QHSE', 'QHSE'), ('RESSOURCES HUMAINES', 'RESSOURCES HUMAINES'), ('SAUVETAGE', 'SAUVETAGE'), ('SUPPLY CHAIN', 'SUPPLY CHAIN'), ('TUYAUTERIE', 'TUYAUTERIE'), ('WICS', 'WICS')], max_length=100),
        ),
        migrations.AddField(
            model_name='periodic_consultation',
            name='societe',
            field=models.CharField(blank=True, choices=[('CARENA', 'CARENA'), ('REGIE', 'REGIE'), ('PRESTATAIRE', 'PRESTATAIRE'), ('AGENT DE BORD', 'AGENT DE BORD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='day_consultation',
            name='accident',
            field=models.CharField(choices=[('Accident reel', 'Accident réel'), ('Accident du trajet', 'Accident du trajet'), ('Accident a la declaration dans le delai de carence de la CNPS', 'Accident à la déclaration dans le délai de carence de la CNPS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='day_consultation',
            name='aptitude',
            field=models.CharField(choices=[('APTE', 'APTE'), ('APTE : avec amenagement', 'APTE : avec aménagement'), ('APTE : avec recommendation', 'APTE : avec récommendation'), ('INAPTE : definitif', 'INAPTE : définitif'), ('INAPTE : temporaire', 'INAPTE : temporaire'), ('INAPTE: au poste mais apte a un autre poste', 'INAPTE: au poste mais apte a un autre poste')], max_length=100),
        ),
        migrations.AlterField(
            model_name='day_consultation',
            name='break_day',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='day_consultation',
            name='pathology',
            field=models.CharField(choices=[('Cardiologie', 'Cardiologie'), ('Dermatologie', 'Dermatologie'), ('Digestive', 'Digestive'), ('Endocrinienne', 'Endocrinienne'), ('Endocrinologie', 'Endocrinologie'), ('Gastro-enterologie', 'Gastro-entérologie'), ('Gynecologie', 'Gynécologie'), ('Hematologie', 'Hématologie'), ('Maladies Infectieuses', 'Maladies Infectieuses'), ('Nephrologie', 'Néphrologie'), ('Neurologie', 'Neurologie'), ('ORL', 'ORL'), ('Ophtalmologie', 'Ophtalmologie'), ('Pneumologie', 'Pneumologie'), ('Psychiatrie', 'Psychiatrie'), ('Rhumatologie', 'Rhumatologie'), ('Stomatologie', 'Stomatologie'), ('Traumatologie', 'Traumatologie'), ('Urologie', 'Urologie'), ('Autres', 'Autres')], max_length=100),
        ),
        migrations.AlterField(
            model_name='day_consultation',
            name='reasons',
            field=models.CharField(choices=[('Accidents', 'Accidents'), ('Consultation generale', 'Consultation générale'), ("Visites d'embauche", "Visites d'embauche"), ('Visites de reprise de travail apres maladie', 'Visites de reprise de travail après maladie'), ('Visites de reprise de travail apres maternite', 'Visites de reprise de travail après maternité'), ('Visites de reprise de travail apres conge annuel', 'Visites de reprise de travail après congé annuel'), ('Visites de reprise de travail apres accident du travail', 'Visites de reprise de travail après accident du travail'), ('Visites de reprise de travail apres maladie professionnelle', 'Visites de reprise de travail après maladie professionnelle'), ('Visites occasionnelle', 'Visites occasionnelle')], max_length=100),
        ),
        migrations.AlterField(
            model_name='day_consultation',
            name='stop',
            field=models.CharField(choices=[('Avec arret', 'Avec arrêt'), ('Sans arret', 'Sans arrêt')], default='Avec arret', max_length=100),
        ),
        migrations.AlterField(
            model_name='periodic_consultation',
            name='aptitude',
            field=models.CharField(choices=[('APTE', 'APTE'), ('APTE : avec amenagement', 'APTE : avec aménagement'), ('APTE : avec recommendation', 'APTE : avec récommendation'), ('INAPTE : definitif', 'INAPTE : définitif'), ('INAPTE : temporaire', 'INAPTE : temporaire'), ('INAPTE: au poste mais apte a un autre poste', 'INAPTE: au poste mais apte a un autre poste')], max_length=100),
        ),
        migrations.AlterField(
            model_name='periodic_consultation',
            name='break_day',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='periodic_consultation',
            name='exam',
            field=models.CharField(choices=[('Audiometrie', 'Audiometrie'), ('Examen ophtalmologique', 'Examen ophtalmologique'), ('NFS, glycenie, proteinurie, glucosurie', 'NFS, glycénie, protéinurie, glucosurie'), ('Numeration formule sanguine', 'Numération formule sanguine'), ('Radiographie des sinus-blondeau', 'Radiographie des sinus-blondeau'), ('Radiographie pulmonaire', 'Radiographie pulmonaire'), ('Spirometrie', 'Spirométrie'), ('Transaminases, uree et creatine', 'Transaminases, urée et créatine'), ('Autres', 'Autres')], max_length=100),
        ),
        migrations.AlterField(
            model_name='periodic_consultation',
            name='pathology',
            field=models.CharField(choices=[('Cardiologie', 'Cardiologie'), ('Dermatologie', 'Dermatologie'), ('Digestive', 'Digestive'), ('Endocrinienne', 'Endocrinienne'), ('Endocrinologie', 'Endocrinologie'), ('Gastro-enterologie', 'Gastro-entérologie'), ('Gynecologie', 'Gynécologie'), ('Hematologie', 'Hématologie'), ('Maladies Infectieuses', 'Maladies Infectieuses'), ('Nephrologie', 'Néphrologie'), ('Neurologie', 'Neurologie'), ('ORL', 'ORL'), ('Ophtalmologie', 'Ophtalmologie'), ('Pneumologie', 'Pneumologie'), ('Psychiatrie', 'Psychiatrie'), ('Rhumatologie', 'Rhumatologie'), ('Stomatologie', 'Stomatologie'), ('Traumatologie', 'Traumatologie'), ('Urologie', 'Urologie'), ('Autres', 'Autres')], max_length=100),
        ),
        migrations.AlterField(
            model_name='periodic_consultation',
            name='reasons',
            field=models.CharField(choices=[('Surveillance medicale annuelle', 'Surveillance médicale annuelle'), ('Surveillance medicale particuliere/specifique', 'Surveillance médicale particulière/spécifique'), ('Surveillance medicale occasionnelle', 'Surveillance médicale occasionnelle')], max_length=100),
        ),
        migrations.AlterField(
            model_name='periodic_consultation',
            name='risks',
            field=models.CharField(choices=[('Nuisance Sonore', 'Nuisance Sonore'), ('Risques lies aux Fumees et Vapeurs Toxiques', 'Risques liés aux fumées et vapeurs toxiques'), ('Risques lies aux poussieres de bois', 'Risques liés aux poussières de bois'), ('Risques lies aux poussieres de sable', 'Risques liés aux poussières de sable'), ('Risques lies aux peintures (diluants, solvants) et vernis', 'Risques liés aux peintures (diluants, solvants) et vernis'), ('Risques lies aux emanations de debris de metaux', 'Risques liés aux émanations de débris de métaux'), ('Risques lies a la plongee (profondeur moins de 15 metres)', 'Risques liés a la plongée (profondeur moins de 15 mètres)'), ('Risques lies aux huiles usagees et degraissants (solvants)', 'Risques liés aux huiles usagées et dégraissants (solvants)')], max_length=100),
        ),
    ]
