# Generated by Django 4.2.2 on 2023-07-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_delete_test_alter_day_consultation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_consultation',
            name='break_day',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodic_consultation',
            name='break_day',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
