# Generated by Django 4.2.2 on 2023-07-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_remove_periodic_consultation_pathology_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodic_consultation',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='periodic_consultation',
            name='risks',
        ),
    ]
