# Generated by Django 4.2.2 on 2023-07-26 08:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_periodic_consultation_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_consultation',
            name='accident',
            field=models.CharField(blank=True, choices=[('Accident reel', 'Accident réel'), ('Accident du trajet', 'Accident du trajet'), ('Accident a la declaration dans le delai de carence de la CNPS', 'Accident à la déclaration dans le délai de carence de la CNPS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='day_consultation',
            name='lesion',
            field=models.CharField(blank=True, choices=[('Amputation', 'Amputation'), ('Atteinte oculaire', 'Atteinte oculaire'), ('Contusion', 'Contusion'), ('Entorse', 'Entorse'), ('Fracture', 'Fracture'), ('Plaie', 'Plaie'), ('Plaie Traumatique', 'Plaie Traumatique'), ('Autres', 'Autres')], max_length=100),
        ),
        migrations.AlterField(
            model_name='day_consultation',
            name='pathology',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cardiologie', 'Cardiologie'), ('Dermatologie', 'Dermatologie'), ('Digestive', 'Digestive'), ('Endocrinienne', 'Endocrinienne'), ('Endocrinologie', 'Endocrinologie'), ('Gastro-enterologie', 'Gastro-entérologie'), ('Gynecologie', 'Gynécologie'), ('Hematologie', 'Hématologie'), ('Maladies Infectieuses', 'Maladies Infectieuses'), ('Nephrologie', 'Néphrologie'), ('Neurologie', 'Neurologie'), ('ORL', 'ORL'), ('Ophtalmologie', 'Ophtalmologie'), ('Pneumologie', 'Pneumologie'), ('Psychiatrie', 'Psychiatrie'), ('Rhumatologie', 'Rhumatologie'), ('Stomatologie', 'Stomatologie'), ('Traumatologie', 'Traumatologie'), ('Urologie', 'Urologie'), ('Autres', 'Autres')], max_length=100),
        ),
        migrations.AlterField(
            model_name='day_consultation',
            name='siege',
            field=models.CharField(blank=True, choices=[('Membre superieur', 'Membre supérieur'), ('Membre inferieur', 'Membre inférieur'), ('Tete', 'Tête'), ('Thorax', 'Thorax'), ('Autres', 'Autres')], max_length=100),
        ),
        migrations.AlterField(
            model_name='periodic_consultation',
            name='exam',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Audiometrie', 'Audiometrie'), ('Examen ophtalmologique', 'Examen ophtalmologique'), ('NFS, glycenie, proteinurie, glucosurie', 'NFS, glycénie, protéinurie, glucosurie'), ('Numeration formule sanguine', 'Numération formule sanguine'), ('Radiographie des sinus-blondeau', 'Radiographie des sinus-blondeau'), ('Radiographie pulmonaire', 'Radiographie pulmonaire'), ('Spirometrie', 'Spirométrie'), ('Transaminases, uree et creatine', 'Transaminases, urée et créatine'), ('Autres', 'Autres')], max_length=100),
        ),
        migrations.AlterField(
            model_name='periodic_consultation',
            name='pathology',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cardiologie', 'Cardiologie'), ('Dermatologie', 'Dermatologie'), ('Digestive', 'Digestive'), ('Endocrinienne', 'Endocrinienne'), ('Endocrinologie', 'Endocrinologie'), ('Gastro-enterologie', 'Gastro-entérologie'), ('Gynecologie', 'Gynécologie'), ('Hematologie', 'Hématologie'), ('Maladies Infectieuses', 'Maladies Infectieuses'), ('Nephrologie', 'Néphrologie'), ('Neurologie', 'Neurologie'), ('ORL', 'ORL'), ('Ophtalmologie', 'Ophtalmologie'), ('Pneumologie', 'Pneumologie'), ('Psychiatrie', 'Psychiatrie'), ('Rhumatologie', 'Rhumatologie'), ('Stomatologie', 'Stomatologie'), ('Traumatologie', 'Traumatologie'), ('Urologie', 'Urologie'), ('Autres', 'Autres')], max_length=100),
        ),
        migrations.AlterField(
            model_name='periodic_consultation',
            name='risks',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Nuisance Sonore', 'Nuisance Sonore'), ('Risques lies aux Fumees et Vapeurs Toxiques', 'Risques liés aux fumées et vapeurs toxiques'), ('Risques lies aux poussieres de bois', 'Risques liés aux poussières de bois'), ('Risques lies aux poussieres de sable', 'Risques liés aux poussières de sable'), ('Risques lies aux peintures (diluants, solvants) et vernis', 'Risques liés aux peintures (diluants, solvants) et vernis'), ('Risques lies aux emanations de debris de metaux', 'Risques liés aux émanations de débris de métaux'), ('Risques lies a la plongee (profondeur moins de 15 metres)', 'Risques liés a la plongée (profondeur moins de 15 mètres)'), ('Risques lies aux huiles usagees et degraissants (solvants)', 'Risques liés aux huiles usagées et dégraissants (solvants)')], max_length=100),
        ),
    ]
