# Generated by Django 4.2.2 on 2023-07-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0012_alter_day_consultation_atelier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_consultation',
            name='stop',
            field=models.CharField(blank=True, choices=[('Avec arret', 'Avec arrêt'), ('Sans arret', 'Sans arrêt')], default='Avec arret', max_length=50),
        ),
    ]
