# Generated by Django 4.2.2 on 2023-08-02 17:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0014_alter_day_consultation_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodic_consultation',
            name='exam',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Audiometrie', 'Audiometrie'), ('ECG', 'ECG'), ('Examen ophtalmologique', 'Examen ophtalmologique'), ('NFS, glycenie, proteinurie, glucosurie', 'NFS, glycénie, protéinurie, glucosurie'), ('Numeration formule sanguine', 'Numération formule sanguine'), ('Radiographie des sinus-blondeau', 'Radiographie des sinus-blondeau'), ('Radiographie pulmonaire', 'Radiographie pulmonaire'), ('Spirometrie', 'Spirométrie'), ('Transaminases, uree et creatine', 'Transaminases, urée et créatine'), ('Autres', 'Autres')], max_length=100),
        ),
    ]
