# Generated by Django 4.2.2 on 2023-08-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0015_alter_periodic_consultation_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_consultation',
            name='reasons',
            field=models.CharField(choices=[('Accidents', 'Accidents'), ('Consultation generale', 'Consultation générale'), ("Visite d'embauche", "Visites d'embauche"), ('Visite de reprise de travail apres maladie', 'Visite de reprise de travail après maladie'), ('Visite de reprise de travail apres maternite', 'Visite de reprise de travail après maternité'), ('Visite de reprise de travail apres conge annuel', 'Visite de reprise de travail après congé annuel'), ('Visite de reprise de travail apres accident du travail', 'Visite de reprise de travail après accident du travail'), ('Visite de reprise de travail apres maladie professionnelle', 'Visite de reprise de travail après maladie professionnelle'), ('Visite occasionnelle', 'Visite occasionnelle')], max_length=100),
        ),
    ]
