# Generated by Django 4.2.2 on 2023-08-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0016_alter_day_consultation_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_consultation',
            name='matricule',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='periodic_consultation',
            name='matricule',
            field=models.CharField(max_length=50),
        ),
    ]
