# Generated by Django 4.2.1 on 2023-06-09 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenoms', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('societe', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Travailleurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenoms', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('atelier', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicaments',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.fournisseurs'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='travailleurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.travailleurs'),
        ),
    ]
