# Generated by Django 4.2.1 on 2023-06-09 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_fournisseurs_travailleurs_medicaments_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.fournisseurs'),
        ),
    ]
