# Generated by Django 4.2.1 on 2023-06-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_transactions_fournisseur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseurs',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='travailleurs',
            options={'ordering': ['nom']},
        ),
    ]
