# Generated by Django 4.2.2 on 2023-06-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_medicaments_seuil_alerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='travailleurs',
            name='societe',
            field=models.CharField(choices=[('CARENA', 'CARENA'), ('REGIS', 'REGIS')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
