# Generated by Django 4.2.2 on 2023-06-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_travailleurs_societe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='travailleurs',
            name='prenoms',
        ),
        migrations.AddField(
            model_name='travailleurs',
            name='societe_regie',
            field=models.CharField(blank=True, choices=[('RMO', 'RMO'), ('SNS', 'SNS'), ('TMS', 'TMS'), ('MIRBAP', 'MIRBAP'), ('CTMCI', 'CTMCI'), ('EKAR', 'EKAR'), ('ETS AF', 'ETS AF'), ('E.A.C.I', 'E.A.C.I'), ('WICS', 'WICS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='travailleurs',
            name='matricule',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='travailleurs',
            name='nom',
            field=models.CharField(max_length=200),
        ),
    ]
