# Generated by Django 4.2.2 on 2023-06-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_delete_notification_remove_travailleurs_prenoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travailleurs',
            name='societe',
            field=models.CharField(choices=[('CARENA', 'CARENA'), ('REGIE', 'REGIE')], max_length=20),
        ),
    ]
