# Generated by Django 4.2.2 on 2023-07-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_alter_travailleurs_atelier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travailleurs',
            name='societe',
            field=models.CharField(choices=[('CARENA', 'CARENA'), ('REGIE', 'REGIE'), ('PRESTATAIRE', 'PRESTATAIRE'), ('REGIE', 'REGIE')], max_length=20),
        ),
    ]
