# Generated by Django 4.2.2 on 2023-07-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_alter_travailleurs_societe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travailleurs',
            name='societe',
            field=models.CharField(choices=[('CARENA', 'CARENA'), ('REGIE', 'REGIE'), ('PRESTATAIRE', 'PRESTATAIRE'), ('AGENT DE BORD', 'AGENT DE BORD')], max_length=20),
        ),
    ]
