# Generated by Django 4.2.2 on 2023-07-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_alter_travailleurs_societe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaments',
            options={'ordering': ['nom_medoc'], 'verbose_name_plural': 'Medicaments'},
        ),
        migrations.AlterModelOptions(
            name='travailleurs',
            options={'ordering': ['nom'], 'verbose_name_plural': 'Travailleurs'},
        ),
    ]
