# Generated by Django 4.2.2 on 2023-07-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_alter_medicaments_options_alter_travailleurs_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaments',
            options={'ordering': ['nom_medoc'], 'verbose_name_plural': 'Médicaments'},
        ),
    ]
