# Generated by Django 4.2.2 on 2023-07-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_medicaments_seuil_alerte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaments',
            name='seuil_alerte',
        ),
    ]
