# Generated by Django 4.2.2 on 2023-07-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_remove_medicaments_seuil_alerte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseurs',
            options={'ordering': ['nom'], 'verbose_name_plural': 'Fournisseurs'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['date_transaction'], 'verbose_name_plural': 'Transactions'},
        ),
    ]
