# Generated by Django 4.2.2 on 2023-08-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_alter_fournisseurs_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaments',
            name='seuil_alerte',
            field=models.CharField(default='', max_length=23),
            preserve_default=False,
        ),
    ]
