# Generated by Django 4.2.2 on 2023-08-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_remove_medicaments_seuil_alerte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaments',
            name='quantité_detail',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='medicaments',
            name='quantité_stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='quantite_plaq',
            field=models.PositiveIntegerField(),
        ),
    ]
