# Generated by Django 4.2.2 on 2023-08-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_alter_medicaments_quantité_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseurs',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicaments',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.fournisseurs'),
        ),
        migrations.AlterField(
            model_name='medicaments',
            name='nom_commercial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicaments',
            name='quantité_detail',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='medicaments',
            name='quantité_stock',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.fournisseurs'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='quantite',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='quantite_plaq',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='travailleurs',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
