# Generated by Django 4.2.2 on 2023-08-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0022_alter_fournisseurs_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaments',
            name='expiration',
            field=models.DateField(default='2024-6-22'),
            preserve_default=False,
        ),
    ]
