# Generated by Django 4.2.2 on 2023-08-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_medicaments_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaments',
            name='plaquette_par_boite',
            field=models.PositiveBigIntegerField(default=10),
            preserve_default=False,
        ),
    ]
