# Generated by Django 4.2.2 on 2023-07-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation_journaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField(auto_now_add=True)),
                ('societe', models.CharField(choices=[('CARENA', 'CARENA'), ('REGIE', 'REGIE'), ('PRESTATAIRE', 'PRESTATAIRE'), ('AGENT DE BORD', 'AGENT DE BORD')], max_length=50)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom_prenoms', models.CharField(max_length=200)),
                ('emploi_occupe', models.CharField(max_length=100)),
                ('atelier', models.CharField(max_length=100)),
                ('type_visite', models.CharField(choices=[('ACCIDENT', 'ACCIDENT'), ('CONSULTATION JOURNALIERE', 'CONSULTATION JOURNALIERE'), ('VISITE MEDICALE DE REPRISE : APRES ACCIDENT', 'VISITE MEDICALE DE REPRISE : APRES ACCIDENT'), ('VISITE MEDICALE DE REPRISE : APRES CONGES', 'VISITE MEDICALE DE REPRISE : APRES CONGES'), ('VISITE MEDICALE DE REPRISE : APRES MALADIE LONGUE DUREE', 'VISITE MEDICALE DE REPRISE : APRES MALADIE LONGUE DUREE'), ('VISITE MEDICALE DE REPRISE : APRES MALADIE PROFESSIONNELLE', 'VISITE MEDICALE DE REPRISE : APRES MALADIE PROFESSIONNELLE'), ('VM EMBAUCHE', 'VM EMBAUCHE'), ('VMR APRES CONGE ANNUEL', 'VMR APRES CONGE ANNUEL'), ('VM OCCASIONNELLE', 'VM OCCASIONNELLE')], max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('affection_connue', models.CharField(choices=[('CARDIO', 'CARDIO'), ('NEPHRO', 'NEPHRO'), ('OPHTALMO', 'OPHTALMO'), ('PNEUMO', 'PNEUMO'), ('RHUMATO', 'RHUMATO'), ('ORL', 'ORL'), ('NEURO', 'NEURO'), ('DERMATO', 'DERMATO'), ('HEMATO', 'HEMATO'), ('DIGESTIVE', 'DIGESTIVE'), ('ENDOCRINIENNE', 'ENDOCRINIENNE'), ('TRAUMATO', 'TRAUMATO'), ('UROLOGIQUE', 'UROLOGIQUE'), ('AUTRES', 'AUTRES')], max_length=15)),
                ('nouvelle_affection', models.CharField(max_length=100)),
                ('observation', models.TextField()),
                ('aptitude', models.CharField(choices=[('APTE', 'APTE'), ('APTE : AVEC AMENAGEMENT', 'APTE : AVEC AMENAGEMENT'), ('INAPTE : TEMPORAIRE', 'INAPTE : TEMPORAIRE'), ('INAPTE : DEFINITIF', 'INAPTE : DEFINITIF'), ('INAPTE: AU POSTE MAIS APTE A UN AUTRE POSTE', 'INAPTE: AU POSTE MAIS APTE A UN AUTRE POSTE')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation_VMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField()),
                ('societe', models.CharField(choices=[('CARENA', 'CARENA'), ('REGIE', 'REGIE'), ('PRESTATAIRE', 'PRESTATAIRE'), ('AGENT DE BORD', 'AGENT DE BORD')], max_length=50)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom_prenoms', models.CharField(max_length=200)),
                ('emploi_occupe', models.CharField(max_length=100)),
                ('atelier', models.CharField(max_length=100)),
                ('type_visite', models.CharField(choices=[('VM ANNUELLE', 'VM ANNUELLE'), ('VM SPECIFIQUE', 'VM SPECIFIQUE')], max_length=100)),
                ('nature_risque', models.CharField(choices=[('NUISANCE SONORE', 'NUISANCE SONORE'), ('RISQUES LIES AUX FUMEES ET VAPEURS TOXIQUES', 'RISQUES LIES AUX FUMEES ET VAPEURS TOXIQUES'), ('RISQUES LIES AUX POUSSIERES DE BOIS', 'RISQUES LIES AUX POUSSIERES DE BOIS'), ('RISQUES LIES AUX POUSSIERES DE SABLE', 'RISQUES LIES AUX POUSSIERES DE SABLE'), ('RISQUE LIE AUX PEINTURES (DILUANT, SOLVANTS) ET VERNIS', 'RISQUE LIE AUX PEINTURES (DILUANT, SOLVANTS) ET VERNIS'), ('RISQUES LIES AUX EMANATIONS DE DEBRIS DE METAUX', 'RISQUES LIES AUX EMANATIONS DE DEBRIS DE METAUX'), ('RISQUES LIES A LA PLONGEE (PROFONDEUR MOINS DE 15 METRES)', 'RISQUES LIES A LA PLONGEE (PROFONDEUR MOINS DE 15 METRES)'), ('RISQUES LIES AUX HUILES USAGEES ET DEGRAISSANTS (SOLVANTS)', 'RISQUES LIES AUX HUILES USAGEES ET DEGRAISSANTS (SOLVANTS)')], max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('examen_realise', models.CharField(choices=[('BIOLOGIE(NFS, TRANSA, CREAT, AUTRES)', 'BIOLOGIE(NFS, TRANSA, CREAT, AUTRES)'), ('RADIOLOGIE(PULMONAIRE, BLONDEAU)', 'RADIOLOGIE(PULMONAIRE, BLONDEAU)'), ('AUDIOMETRIE', 'AUDIOMETRIE'), ('OPHTALMOLOGIE(AV, FO, VC, VR)', 'OPHTALMOLOGIE(AV, FO, VC, VR)'), ('SPIROMETRIE', 'SPIROMETRIE'), ('EXAMEN CLINIQUE', 'EXAMEN CLINIQUE')], max_length=100)),
                ('affection_connue', models.CharField(choices=[('CARDIO', 'CARDIO'), ('NEPHRO', 'NEPHRO'), ('OPHTALMO', 'OPHTALMO'), ('PNEUMO', 'PNEUMO'), ('RHUMATO', 'RHUMATO'), ('ORL', 'ORL'), ('NEURO', 'NEURO'), ('DERMATO', 'DERMATO'), ('HEMATO', 'HEMATO'), ('DIGESTIVE', 'DIGESTIVE'), ('ENDOCRINIENNE', 'ENDOCRINIENNE'), ('TRAUMATO', 'TRAUMATO'), ('UROLOGIQUE', 'UROLOGIQUE'), ('AUTRES', 'AUTRES')], max_length=15)),
                ('nouvelle_affection', models.CharField(max_length=100)),
                ('observation', models.TextField()),
                ('aptitude', models.CharField(choices=[('APTE', 'APTE'), ('APTE : AVEC AMENAGEMENT', 'APTE : AVEC AMENAGEMENT'), ('INAPTE : TEMPORAIRE', 'INAPTE : TEMPORAIRE'), ('INAPTE : DEFINITIF', 'INAPTE : DEFINITIF'), ('INAPTE: AU POSTE MAIS APTE A UN AUTRE POSTE', 'INAPTE: AU POSTE MAIS APTE A UN AUTRE POSTE')], max_length=100)),
            ],
        ),
    ]
