# Generated by Django 4.2.2 on 2023-07-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_alter_consultation_journaliere_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation_vma',
            name='affection_connue',
        ),
        migrations.RemoveField(
            model_name='consultation_vma',
            name='age',
        ),
        migrations.RemoveField(
            model_name='consultation_vma',
            name='aptitude',
        ),
        migrations.RemoveField(
            model_name='consultation_vma',
            name='atelier',
        ),
        migrations.RemoveField(
            model_name='consultation_vma',
            name='emploi_occupe',
        ),
        migrations.RemoveField(
            model_name='consultation_vma',
            name='examen_realise',
        ),
        migrations.RemoveField(
            model_name='consultation_vma',
            name='nature_risque',
        ),
        migrations.RemoveField(
            model_name='consultation_vma',
            name='nouvelle_affection',
        ),
        migrations.RemoveField(
            model_name='consultation_vma',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='consultation_vma',
            name='type_visite',
        ),
    ]
