# Generated by Django 4.2.2 on 2023-07-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_consultation_vma_affection_connue_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultation_VMA',
        ),
    ]
