# Generated by Django 4.2.2 on 2023-07-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_consultation_vma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation_vma',
            name='date_consultation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
