# Generated by Django 4.2.2 on 2023-07-11 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_alter_travailleurs_atelier'),
        ('consultation', '0007_alter_consultation_vma_date_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation_vma',
            name='travailleurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.travailleurs'),
        ),
    ]
