# Generated by Django 4.2.2 on 2023-07-11 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_alter_travailleurs_societe'),
        ('consultation', '0009_alter_consultation_vma_atelier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation_journaliere',
            name='travailleurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.travailleurs'),
        ),
        migrations.AlterField(
            model_name='consultation_journaliere',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='consultation_journaliere',
            name='atelier',
            field=models.CharField(blank=True, choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('BOURBON', 'BOURBON'), ('CHAUDRONNERIE', 'CHAUDRONNERIE'), ('CHARPENTE MENUISERIE', 'CHARPENTE MENUISERIE'), ('COMPTABILITE FINANCE', 'COMPTABILITE FINANCE'), ('ELECTRICITE', 'ELECTRICITE'), ('G4S', 'G4S'), ('INFORMATIQUE ET TELECOM', 'INFORMATIQUE ET TELECOM'), ('IRIS', 'IRIS'), ('MAGASIN', 'MAGASIN'), ('MACHINE OUTILS', 'MACHINE OUTILS'), ('MAINTENANCE & TRAVAUX NEUFS', 'MAINTENANCE & TRAVAUX NEUFS'), ('MANUTENTION ET LEVAGE', 'MANUTENTION ET LEVAGE'), ('MECANIQUE BRD', 'MECANIQUE BRD'), ('NAVIRE', 'NAVIRE'), ('NETTOYAGE INDUSTRIEL', 'NETTOYAGE INDUSTRIEL'), ('PEINTURE', 'PEINTURE'), ('PEINTURE ANTICORROSION', 'PEINTURE ANTICORROSION'), ('PRODUCTION', 'PRODUCTION'), ('QUALITE ENVIRONNEMENT HYGIENE', 'QUALITE ENVIRONNEMENT HYGIENE'), ('QUALITE ENVIRONNEMENT HYGIENE ET SECURITE', 'QUALITE ENVIRONNEMENT HYGIENE ET SECURITE'), ('QHSE', 'QHSE'), ('RESSOURCES HUMAINES', 'RESSOURCES HUMAINES'), ('SAUVETAGE', 'SAUVETAGE'), ('SUPPLY CHAIN', 'SUPPLY CHAIN'), ('TUYAUTERIE', 'TUYAUTERIE'), ('WICS', 'WICS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='consultation_journaliere',
            name='nom_prenoms',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='consultation_journaliere',
            name='societe',
            field=models.CharField(blank=True, choices=[('CARENA', 'CARENA'), ('REGIE', 'REGIE'), ('PRESTATAIRE', 'PRESTATAIRE'), ('REGIE', 'REGIE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='consultation_vma',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
