# Generated by Django 4.2.2 on 2023-07-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0010_consultation_journaliere_travailleurs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation_journaliere',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
